services:
  db:
    image: postgres:14.18-bookworm
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgresdbpass
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
